# .github/workflows/build.yml
name: Build on Linux
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y g++-12 gcc-12 ninja-build libgtk-3-dev libasound2-dev libjack-jackd2-dev pkg-config       
          sudo apt-get update && sudo apt-get install -y build-essential
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build/
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Clean Cache
        run: rm -f build/CMakeCache.txt && rm -rf build/CMakeFiles
      - name: Configure CMake
        run: cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=g++-12 .
      - name: Build with Ninja
        run: ninja -C build
      - name: List build directory 
        run: ls -Rlh build |grep Sorta
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sorta-build
          path: build/Sorta_artefacts/Sorta
